### ISSUE TITLE
Error while installing. CSSharp: CoreConfig file not found, creating one from example.

### ISSUE THREAD

**Issue by LeRoid-hub** [roflmuffin/CounterStrikeSharp#237]
Happy new Year.

I tried to install this.
First i installed metamod and then i copied the CSS addon folder.
I both used release 142 and 141 and both failed in the same way.

I hope my documentation are Sufficient and somebody can help me.
Thanks for your help.

## Logs
```
Attaching to cs2-dedicated
cs2-dedicated  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
cs2-dedicated  | Logging directory: '/home/steam/Steam/logs'
cs2-dedicated  | [  0%] Checking for available updates...
cs2-dedicated  | [----] Verifying installation...
cs2-dedicated  | Steam Console Client (c) Valve Corporation - version 1702079268
cs2-dedicated  | -- type 'quit' to exit --
cs2-dedicated  | Loading Steam API...OK
cs2-dedicated  |
cs2-dedicated  | Connecting anonymously to Steam Public...OK
cs2-dedicated  | Waiting for client config...OK
cs2-dedicated  | Waiting for user info...OK
cs2-dedicated  | Success! App '730' already up to date.
cs2-dedicated  | pre-hook: noop
cs2-dedicated  | Starting CS2 Dedicated Server
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libengine2.so, got 0x557f26ac64d0
cs2-dedicated  |
cs2-dedicated  | Console initialized.
cs2-dedicated  | Steam AppId(730), BreakpadId(2347771)
cs2-dedicated  | InitSteamLogin_Internal: Initializing breakpad.
cs2-dedicated  | Using breakpad crash handler
cs2-dedicated  | Steam Universe is invalid, possibly asking before Steam was successfully initialized.
cs2-dedicated  | ResetBreakpadAppId: Universe is 0 (k_EUniverseInvalid)
cs2-dedicated  | ResetBreakpadAppId: Setting dedicated server app id: 2347773
cs2-dedicated  | Setting breakpad minidump AppID = 2347773
cs2-dedicated  | Forcing breakpad minidump interfaces to load
cs2-dedicated  | Looking up breakpad interfaces from steamclient
cs2-dedicated  | Calling BreakpadMiniDumpSystemInit
cs2-dedicated  | Loaded libSDL3.so.0, got 0x557f26bc7b80
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libtier0.so, got 0x557f26ab0290
cs2-dedicated  | Visibility enabled.
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x557f26bc8040
cs2-dedicated  | Unknown read error 21
cs2-dedicated  | USRLOCAL path not found!
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/liblocalize.so, got 0x557f26bda570
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/librendersystemempty.so, got 0x557f26bec670
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x557f26bfeba0
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libschemasystem.so, got 0x557f26c10ca0
cs2-dedicated  | Trying to set dxlevel (111) which is higher than the card can support (110)!
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libmaterialsystem2.so, got 0x557f26c231c0
cs2-dedicated  | ---------------
cs2-dedicated  | Path ID:             File Path:
cs2-dedicated  | ADDONS               "/home/steam/cs2-dedicated/game/csgo_addons/"
cs2-dedicated  | CONTENT              "/home/steam/cs2-dedicated/content/csgo/addons/metamod/"
cs2-dedicated  | CONTENT              "/home/steam/cs2-dedicated/content/csgo/"
cs2-dedicated  | CONTENT              "/home/steam/cs2-dedicated/content/csgo_imported/"
cs2-dedicated  | CONTENT              "/home/steam/cs2-dedicated/content/csgo_core/"
cs2-dedicated  | CONTENT              "/home/steam/cs2-dedicated/content/core/"
cs2-dedicated  | CONTENTADDONS        "/home/steam/cs2-dedicated/content/csgo_addons/"
cs2-dedicated  | CONTENTROOT          "/home/steam/cs2-dedicated/content/"
cs2-dedicated  | DEFAULT_WRITE_PATH   "/home/steam/cs2-dedicated/game/csgo/addons/metamod/"
cs2-dedicated  | EXECUTABLE_PATH      "/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/"
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/csgo/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo/pak01.vpk
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/csgo_core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_core/pak01.vpk
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/core/pak01.vpk
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/csgo/addons/metamod/"
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/csgo/"
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/csgo_imported/"
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/csgo_core/"
cs2-dedicated  | GAME                 "/home/steam/cs2-dedicated/game/core/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo/addons/metamod/bin/linuxsteamrt64/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo/addons/metamod/bin/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo/bin/linuxsteamrt64/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo/bin/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_imported/bin/linuxsteamrt64/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_imported/bin/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_core/bin/linuxsteamrt64/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_core/bin/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/core/bin/linuxsteamrt64/"
cs2-dedicated  | GAMEBIN              "/home/steam/cs2-dedicated/game/core/bin/"
cs2-dedicated  | GAMEROOT             "/home/steam/cs2-dedicated/game/"
cs2-dedicated  | MOD                  "/home/steam/cs2-dedicated/game/csgo/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo/pak01.vpk
cs2-dedicated  | MOD                  "/home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk
cs2-dedicated  | MOD                  "/home/steam/cs2-dedicated/game/csgo_core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_core/pak01.vpk
cs2-dedicated  | MOD                  "/home/steam/cs2-dedicated/game/csgo/"
cs2-dedicated  | MOD                  "/home/steam/cs2-dedicated/game/csgo_imported/"
cs2-dedicated  | MOD                  "/home/steam/cs2-dedicated/game/csgo_core/"
cs2-dedicated  | PLATFORM             "/home/steam/cs2-dedicated/game/core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/core/pak01.vpk
cs2-dedicated  | PLATFORM             "/home/steam/cs2-dedicated/game/core/"
cs2-dedicated  | SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/csgo/addons/metamod/"
cs2-dedicated  | SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/csgo/"
cs2-dedicated  | SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/csgo_imported/"
cs2-dedicated  | SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/csgo_core/"
cs2-dedicated  | SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/core/"
cs2-dedicated  | SHADER_SOURCE_MOD    "/home/steam/cs2-dedicated/src/shaders/csgo/addons/metamod/"
cs2-dedicated  | SHADER_SOURCE_ROOT   "/home/steam/cs2-dedicated/src/shaders/"
cs2-dedicated  | command line arguments:
cs2-dedicated  | -dedicated -ip 0.0.0.0 -port 27015 -console -usercon -maxplayers 10 +game_alias competitive +mapgroup mg_active +map de_nuke +sv_setsteamaccount C678E4E2694E97F3F5B0058C52B82487 +sv_lan 0
cs2-dedicated  | protected command line arguments (stripped from above):
cs2-dedicated  | +rcon_password <protected> +sv_password <protected>
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libmeshsystem.so, got 0x557f26c356e0
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libworldrenderer.so, got 0x557f26c47c00
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libpulse_system.so, got 0x557f26c5a540
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libvscript.so, got 0x557f26c6ef20
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libnetworksystem.so, got 0x557f26c81020
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libanimationsystem.so, got 0x557f26c95220
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libvphysics2.so, got 0x557f26cab520
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libsoundsystem.so, got 0x557f26cbe280
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libscenesystem.so, got 0x557f26cd4580
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libv8system.so, got 0x557f26ce9c20
cs2-dedicated  | Network System Initialized
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so, got (nil)
cs2-dedicated  |  failed to dlopen /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so error=/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
cs2-dedicated  |  failed to dlopen "/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so" error=/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
cs2-dedicated  | Loaded libserver_valve.so, got (nil)
cs2-dedicated  |  failed to dlopen libserver_valve.so error=libserver_valve.so: cannot open shared object file: No such file or directory
cs2-dedicated  |  failed to dlopen "libserver_valve.so" error=libserver_valve.so: cannot open shared object file: No such file or directory
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/csgo/addons/metamod/bin/linuxsteamrt64/libserver.so, got 0x557f26d03a30
cs2-dedicated  | Physics Console Communications is not initialized
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libengine2.so, got 0x557f26ac64d0
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/csgo/bin/linuxsteamrt64/libhost.so, got 0x557f26d34b30
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libscenefilecache.so, got 0x557f26d47cb0
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libparticles.so, got 0x557f26d5a1d0
cs2-dedicated  | Loaded /home/steam/cs2-dedicated/game/csgo/bin/linuxsteamrt64/libmatchmaking.so, got 0x557f26d6d770
cs2-dedicated  | No .vcds loaded or no scenes/scenes.vrman
cs2-dedicated  | GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
cs2-dedicated  | GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
cs2-dedicated  | GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
cs2-dedicated  | [00:40:23.345] CSSharp: Initializing
cs2-dedicated  | [00:40:23.345] CSSharp: CoreConfig file not found, creating one from example.
cs2-dedicated  | [00:40:23.345] CSSharp: CoreConfig file not found, creating one from example.
```

Hundreds oh these : cs2-dedicated  | [00:40:23.345] CSSharp: CoreConfig file not found, creating one from example. 
Just the Number  [00:40:23.345] is incrementing

```
cs2-dedicated  | [00:40:25.574] CSSharp: CoreConfig file not found, creating one from example.
cs2-dedicated  | [00:40:25.574] CSSharp: CoreConfig file not found, creating one from example.
cs2-dedicated  | [00:40:25.574] CSSharp: CoreConfig file not found, creating one from example.
cs2-dedicated  | entry.sh: line 94:    35 Segmentation fault      (core dumped) ./cs2 -dedicated -ip 0.0.0.0 -port 27015 -console -usercon -maxplayers 10 +game_alias competitive +mapgroup mg_active +map de_nuke +rcon_password rconpw +sv_setsteamaccount MYTOKEN +sv_password pw +sv_lan 0
cs2-dedicated  | post-hook: noop
cs2-dedicated exited with code 0
```

## DOCKER Compose
```
version: '3.7'
services:
  cs2-server:
    image: joedwards32/cs2
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: cs2-dedicated
    environment:
      # Server configuration
      - SRCDS_TOKEN=MYTOKEN                 # Game Server Token from https://steamcommunity.com/dev/managegameservers
      - CS2_SERVERNAME=Name     # (Set the visible name for your private server)
      - CS2_CHEATS=0                # (0 - disable cheats, 1 - enable cheats)
      - CS2_PORT=27015              # (CS2 server listen port tcp_udp)
      - CS2_SERVER_HIBERNATE=1      # (Put server in a low CPU state when there are no players. 0 - hibernation disabled, 1 - hibernation enabled)
      - CS2_RCON_PORT               # (Optional, use a simple TCP proxy to have RCON listen on an alternative port. Useful for services like AWS Fargate which do not support mixed protocol ports.)
      - CS2_LAN=0                   # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      - CS2_RCONPW=rconpw         # (RCON password)
      - CS2_PW=pw                     # (CS2 server password)
      - CS2_MAXPLAYERS=10           # (Max players)
      - CS2_ADDITIONAL_ARGS         # (Optional additional arguments to pass into cs2)
      # Game modes
      - CS2_GAMEALIAS=competitive               # (Game type, e.g. casual, competitive, deathmatch. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMETYPE=0              # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMEMODE=1              # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_MAPGROUP=mg_active      # (Map pool)
      - CS2_STARTMAP=de_nuke        # (Start map)
      # Bots
      - CS2_BOT_DIFFICULTY          # (0 - easy, 1 - normal, 2 - hard, 3 - expert)
      - CS2_BOT_QUOTA               # (Number of bots)
      - CS2_BOT_QUOTA_MODE          # (fill, competitive)
      # TV
      - TV_AUTORECORD=0             # Automatically records all games as CSTV demos: 0=off, 1=on.
      - TV_ENABLE=0                 # Activates CSTV on server: 0=off, 1=on.
      - TV_PORT=27020               # Host SourceTV port
      - TV_PW=changeme              # CSTV password for clients
      - TV_RELAY_PW=changeme        # CSTV password for relay proxies
      - TV_MAXRATE=0                # World snapshots to broadcast per second. Affects camera tickrate.
      - TV_DELAY=0                  # Max CSTV spectator bandwidth rate allowed, 0 == unlimited
    volumes:
      - cs2:/home/steam/cs2-dedicated/  # (Change /mnt/cs2 according to your volume location)
    ports:
      - "27015:27015/tcp"           # TCP
      - "27015:27015/udp"           # UDP
      - "27020:27020/udp"           # UDP
volumes:
  cs2:
```

## gameinfo.gi
```
"GameInfo"
{
	// ********************************************************************************
	// ********************************************************************************
	// ********************************************************************************
	// DO NOT EDIT THIS FILE DIRECTLY - YOU PROBABLY WANT TO EDIT CSGO_CORE/GAMEINFO.GI
	// ********************************************************************************
	// ********************************************************************************
	// ********************************************************************************

	game 		"Counter-Strike 2"
	title 		"Counter-Strike 2"
	title_pw	"E58F8DE68190E7B2BEE88BB1EFBC9AE585A8E79083E694BBE58ABF"
	
	LayeredOnMod	csgo_imported // Inherits the gameinfo.gi data from csgo_imported (which itself inherits from csgo_core)

	FileSystem
	{
		SearchPaths
		{
			Game_LowViolence	csgo_lv // Perfect World content override

			Game 	csgo/addons/metamod
			Game	csgo
``` 

## File structure

├── counterstrikesharp
│   ├── api
│   ├── bin
│   ├── configs
│   ├── dotnet
│   ├── gamedata
│   ├── plugins
│   └── source
├── metamod
│   ├── bin
│   ├── counterstrikesharp.vdf
│   ├── metaplugins.ini
│   └── README.txt
├── metamod.vdf
└── metamod_x64.vdf
